### PR TITLE
General Bug Fixes

### PR DESCRIPTION
**Pull request by lveez**
Fixed several bugs:
- Five not starting if power was turned off (Issue #36)
- Window setting not being consistent on Five (Issue #32)
- Five Doc rounds being enabled even when the option was set to none.

I also added an example of a .bat file that can be used to launch directly into the strat tester mod. If you decide to add the .bat to a release might be worth mentioning in the readme that you can make a shortcut to it and add it to the start menu/desktop/taskbar.

### CODE REVIEW

**Comment by TTS4life** [comment]
You should update the bat file to start with ```cd ../../bin``` instead just ```cd bin``` so that users do not need to move the `.bat` file to the root of their BO1 folder for it to work (or we have to change how we bundle our releases to accommodate for it being put into the right spot). Once that's updated I'm ready to merge.

**Comment by lveez** [comment]
Modified the file so it can be placed anywhere in the Black Ops directory up to mods/Strat Tester, since I personally prefer having it in the root directory. This way people can move it if they want or leave it there if they don't.

**Comment by 5and5** [comment]
@lveez I've added you as a collaborator so you won't have to make pull requests in the future.

**Comment by lveez** [comment]
Thank you :)

As far as I can tell none of the commits were transferred over to 5and5:main, not entirely sure why. Easiest fix is probably for me to redo the changes when I get a chance and just push them to main.

**Comment by 5and5** [comment]
I think I fixed it.

**Pull request merged**
